### ISSUE TITLE
Update maps links

### ISSUE THREAD

**Issue by colinbrislawn** [CamerataMusica/website#47]
For Kennewick First Presbyterian Church, use this: https://goo.gl/maps/quHQSkdBnScDHqh26 

For CBC Theatre, use https://goo.gl/maps/kNZ4DFSqJUNVorCE6 (updated!)

Possible custom maps with [Prettymaps](https://github.com/marceloprates/prettymaps)

**Comment by jcdoran** [comment]
Hi Colin -

I’ve been getting a few of these announcements lately, but I’m no longer on the Camerata Musica board (nor is Nancy),so I assume they should be going to somebody else (Ramesh?). Please take me off the distribution list.  Thanks.

I hope you’re doing well.

Chris



On Aug 31, 2022, at 6:53 PM, Colin Brislawn ***@***.***> wrote:


For Kennewick First Presbyterian Church, use this: https://goo.gl/maps/quHQSkdBnScDHqh26 <https://goo.gl/maps/quHQSkdBnScDHqh26>
For CBC Theatre, use https://goo.gl/maps/4BhdA4AZzD3WH72B7 <https://goo.gl/maps/4BhdA4AZzD3WH72B7> then update once Theatre is added to Google

**Comment by colinbrislawn** [comment]
Thanks, Chris! Yes, I'll remove you from the GitHub team
